stressng integration
cloud-bulldozer/benchmark-operator pull request #412
Opened 2020-09-17 09:07 UTC by mkarg75

ssia

2020-09-18 18:26 UTC, rsevilla87 requested changes

2020-09-18 18:26 UTC, rsevilla87 commented on roles/stressng/templates/stressng_workload.yml.j2
> +             run_snafu --tool stressng -u {{ uuid }}"
Append -j /workload/jobfile

2020-09-22 13:33 UTC, smalleni commented on docs/stressng.md
> +The stressng benchmark is divided into 3 subsystems, driven by so-called stressors. In the above example we have cpu stressors, virtual machine (vm) stressors and memory stressors. They are running i
Did you mean virtual memory instead?

2020-09-23 19:38 UTC, jtaleric commented
/rerun all

2020-09-24 09:38 UTC, rsevilla87 commented
@mkarg75 there're some conflicts in README.md, can you fix them?

2020-09-28 06:43 UTC, mkarg75 commented
Should be sorted.

2020-09-28 08:40 UTC, rsevilla87 requested changes

2020-09-28 08:40 UTC, rsevilla87 commented on tests/test_crs/valid_stressng.yaml
> +    port: 80
Hey @mkarg75, can you replace these two by:

```suggestion
    server: ES_SERVER
    port: ES_PORT
```
These names are replaced by the CI.

2020-09-29 12:21 UTC, dry923 commented
/rerun all tests/test_stressng.sh

2020-09-29 12:34 UTC, dry923 commented on roles/stressng/tasks/main.yaml
> +        complete: true
this line should say complete: false or be removed

2020-09-29 12:37 UTC, dry923 commented
/rerun all tests/test_stressng.sh

2020-09-29 12:54 UTC, dry923 commented
/rerun all

2020-09-29 12:55 UTC, dry923 commented on README.md
> +| [stressng](docs/stressng.md)   | Stress system resources | Working            |                 | Not Supported         | Not Supported  |
Can you add "Used, default : 3second" for the reconciliation usage section since you have added that?

2020-10-13 10:16 UTC, rsevilla87 approved these changes
LGTM!

2020-10-13 10:35 UTC, dry923 approved these changes
LGTM!

2020-10-13 10:36 UTC, merged