Option to send fio results to client pod log
cloud-bulldozer/benchmark-operator pull request #427
Opened 2020-10-02 14:49 UTC by fritchie

This commit adds the ability to send fio results to the client pod
logs. This was bought up in

https://github.com/cloud-bulldozer/benchmark-operator/issues/417

If workload_args include

fio_json_to_log: true

all the fio-result.json files found in /tmp/fiod-$uuid will
be sent to the log.

2020-10-02 15:21 UTC, jtaleric commented
@bengland2 @acalhounRH Can I get one of you two +1 this....

2020-10-07 13:28 UTC, jtaleric approved these changes
LGTM

2020-10-07 13:36 UTC, rsevilla87 requested changes
Hey @fritchie, mind you add this new parameter to the docs?

2020-10-07 13:36 UTC, acalhounRH commented
Can we add a logging statement, something like FIO JSON OUTPUT for fiod-{{ uuid }}. that way we can search for the text and make finding the exact sample(s) faster.

2020-10-07 13:50 UTC, acalhounRH commented
Okay, so the current way that this is printing out the json files they will be strung together and IMHO will be too messy to make sense of. I would recommend moving this piece of code into the the for-loop on line 74, that way the output is next to benchmark-wrappers execution and there is a clear delineation between samples.

I would not merge as is due to this.

2020-10-07 13:54 UTC, fritchie commented
> Can we add a logging statement, something like FIO JSON OUTPUT for fiod-{{ uuid }}. that way we can search for the text and make finding the exact sample(s) faster.

I just used START and END with the filename:

echo START...$jsonfile;cat $jsonfile;echo END...$jsonfile

but I can change to something more pronounced

2020-10-08 16:02 UTC, fritchie commented
Requested changes have been made.

2020-10-08 16:05 UTC, rsevilla87 approved these changes
LGTM!

2020-10-12 16:02 UTC, jtaleric approved these changes
LGTM

2020-10-12 16:06 UTC, acalhounRH approved these changes
LGTM

2020-10-12 16:09 UTC, merged