Create Helm Chart for benchmark-operator
cloud-bulldozer/benchmark-operator pull request #503
Opened 2020-12-15 15:34 UTC by whitleykeith

This PR creates a helm chart for the benchmark-operator, which can be used to provide an easier installation experience compared to the current process.

With this chart, installing the operator only requires the following:

```bash
oc adm policy -n my-ripsaw add-scc-to-user privileged -z benchmark-operator
helm install ripsaw $CHART_PATH -n my-ripsaw --create-namespace
```

deleting the operator is also simple, requiring the following:

```bash
helm delete ripsaw -n my-ripsaw --purge
```

It's also much easier to parameterize things through the use of Helm Values. For example, changing the operator image and tag is done in the same line as the install:

```bash
cd charts/benchmark-operator
helm install ripsaw . -n my-ripsaw --create-namespace --set operator.image.repository=$OPERATOR_REPO,operator.image.tag=$OPERATOR_TAG
```

2020-12-17 20:49 UTC, jtaleric requested changes
I am not too familiar with Helm, but this seems to be missing a readme and test for the Helm install... i wonder if we could add a simple test to install via the helm chart?

2020-12-21 15:30 UTC, whitleykeith commented
@jtaleric I added a README for the helm chart, but I'm not sure how to handle adding a test with the E2E refactoring pending since it would create a good bit of conflicts

2020-12-23 11:31 UTC, rsevilla87 commented on charts/benchmark-operator/templates/operator.yaml
> +          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default "master" }}"
Why don't you default this variable in the values.yaml file?

2020-12-23 11:33 UTC, rsevilla87 commented on charts/benchmark-operator/templates/serivce-account.yaml
> +apiVersion: v1
s/serivce-account.yaml/service-account.yaml

2020-12-23 11:59 UTC, rsevilla87 requested changes
Just a couple of small nits

2020-12-23 21:41 UTC, chaitanyaenr reviewed
Minor nit, otherwise LGTM.

2020-12-23 21:41 UTC, chaitanyaenr commented on README.md
> +helm install benchmark-operator . -n my-ripsaw --create-namespace
We might want to mention that helm needs to be installed on the box and may be also include the helm command to delete the operator that you have in the commit message.

2021-01-07 18:37 UTC, rsevilla87 approved these changes
LGTM!, nice work @whitleykeith

2021-01-07 18:39 UTC, chaitanyaenr approved these changes
LGTM

2021-01-07 18:40 UTC, merged