Add pod-density scenarios
cloud-bulldozer/benchmark-operator pull request #528
Opened 2021-02-18 20:54 UTC by smalleni

This scenarios is useful when you only care about creatinga  lot of
pods in a namespace and don't care about sitribution across worker nodes.
This is similar to what used to be called pod-vertical.

Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

2021-02-18 21:49 UTC, jtaleric commented on roles/kube-burner/tasks/main.yml
> +  - name: Create node-density/pod-density configmaps
just add an or

2021-02-18 21:50 UTC, jtaleric approved these changes
minor nit, overall looks good.

2021-02-19 18:31 UTC, smalleni commented on roles/kube-burner/tasks/main.yml
> +  - name: Create node-density/pod-density configmaps
Done

2021-02-22 12:18 UTC, rsevilla87 requested changes
Hey @smalleni !,
Can you make reference of this new workload in the docs?

2021-02-22 13:11 UTC, chaitanyaenr approved these changes
LGTM

2021-03-05 14:59 UTC, smalleni commented
> Hey @smalleni !,
> Can you make reference of this new workload in the docs?

Thanks for the reminder Raul, can you take a look now?

2021-03-05 15:00 UTC, rsevilla87 commented
> > Hey @smalleni !,
> > Can you make reference of this new workload in the docs?
> 
> Thanks for the reminder Raul, can you take a look now?

lets wait for CI and MERGE!

2021-03-05 15:18 UTC, merged