add networkpolicy-multitenant case for kube-burner
cloud-bulldozer/benchmark-operator pull request #588
Opened 2021-06-11 18:47 UTC by mohit-sheth

### Description

### Fixes

2021-06-18 12:35 UTC, rsevilla87 commented on roles/kube-burner/files/nginx-deployment.yaml
> +        - containerPort: 80
Container port is 8080 for this container image.

2021-06-18 12:37 UTC, rsevilla87 commented
LGTM so far, I'm currently working on a mechanism to verify policy enforcement. Will add a commit to this PR as soon as I have something.

2021-07-07 18:31 UTC, jtaleric reviewed
Random placeholder about the Quay image.

2021-07-07 18:31 UTC, jtaleric commented on resources/operator.yaml
> +          image: quay.io/msheth/benchmark-operator:test
If this is ready for merge we should swap this back.

2021-07-07 18:32 UTC, jtaleric requested changes
Can we get a test added please

2021-07-14 20:15 UTC, sjug approved these changes
Given the scope discussed with Mohit, this looks good to me.
We're banking entirely on the default-deny network policy application given our scraper pod is outside all created namespaces. Hopefully if the deny policy applied successfully, the rest of them have been as well. 
We don't really have any performance metrics for timing given the policies seem to be applied prior to even the first curl to the various pods.
It may be useful to have a Prometheus metric that exposes the count of currently applied network policies.

2021-07-26 12:22 UTC, rsevilla87 commented on roles/kube-burner/files/case2-networkpolicy.yaml
> +  name: case2-{{.podselector_label}}{{.Replica}}-{{.ingress_label}}-{{randInteger 0 1000000}}
{{randInteger 0 1000000}} is not necessary in all networkpolicy objects

2021-07-30 17:18 UTC, merged

2021-08-02 11:16 UTC, rsevilla87 reviewed
Added some comments

2021-08-03 14:28 UTC, mohit-sheth commented on roles/kube-burner/files/cross-ns-networkpolicy.yaml
> +      label1: foo-{{randInteger 1 5}}
yes, I am trying to follow
```
For each unique label in each Namespace, create a NetworkPolicy with that label as the podSelector, allowing traffic from pods with some other randomly-selected Pod label and randomly-selected Namespace label.
```

hence using the randinteger