Fix image names
cloud-bulldozer/benchmark-operator pull request #715
Opened 2021-11-29 10:33 UTC by chentex

### Description

Inconsistencies on naming have been having negative effects on our automation on image building.

- Rename iperf3 image to iperf
- Rename ycsb-server image to ycsb
- Rename fs-drift image to fs_drift
- Rename fs-drift tool to fs_drift

### Fixes

https://github.com/cloud-bulldozer/benchmark-wrapper/issues/347

2021-11-30 04:38 UTC, learnitall requested changes
Took a look, here are the main things I notice:

* Role names weren't changed. Do we want to change these too? Might as well right since we're at it?
* scale tool name wasn't changed in the scale_openshift template (https://github.com/cloud-bulldozer/benchmark-operator/blob/ae117009213f322b069a324649ed9916b41a006d/roles/scale_openshift/templates/scale.yml#L83)
* iperf test name is still at iperf3

Tomorrow I'll try to do a more thorough look with grep to see if there are other things we're missing here or want to take into consideration.

2021-11-30 04:38 UTC, learnitall commented on tests/test_list
>  test_iperf3.sh
Do we need to change iperf3 -> iperf here as well?

2021-12-23 15:09 UTC, jtaleric commented
Still relevant... Let's work to close this out in the new year

2022-01-09 20:38 UTC, jtaleric commented
still relevant

2022-01-25 12:42 UTC, rsevilla87 commented
Hey @chentex, seems we're hitting this error in CI
```
   hammerdb-standard35/39 in 1586 sec ✓ hammerdb-standard [242122]
   fs_drift-standard36/39 in 1586 sec ✗ fs_drift-standard [1675]
   (in test file ./017-fs_drift.bats, line 13)
     `envsubst < ${CR} | kubectl apply -f -' failed
   The Benchmark "fs_drift-benchmark" is invalid: metadata.name: Invalid value: "fs_drift-benchmark": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
   fs_drift-hostpath37/39 in 1586 sec ✗ fs_drift-hostpath [1799]
   (in test file ./017-fs_drift.bats, line 23)
     `envsubst < ${CR} | kubectl apply -f -' failed
   The Benchmark "fs_drift-hostpath-benchmark" is invalid: metadata.name: Invalid value: "fs_drift-hostpath-benchmark": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

2022-02-14 09:31 UTC, chentex commented
Hey, Raúl, thanks for letting me know, I think this is still a WIP, there is a team meeting that we need to have to discuss the names and the way we were automatically building the images, not everyone was onboard on changing them, I will add them to this weeks meeting to take on it again.

2022-03-27 03:07 UTC, closed without merging