Uperf workload with nodeport and loadbalancer type svc
cloud-bulldozer/benchmark-operator pull request #721
Opened 2022-01-18 23:38 UTC by mukrishn

### Description
To support different service types for uperf workload
NodePort: 
```
      serviceip: true
      servicetype: "nodeport"
```

Loadbalancer: only tested for `metallb` loadbalancers on baremetal.
```
      serviceip: true
      servicetype: "metallb"
      metallb:
        addresspool: "addresspool-l3"
        service_etp: "Cluster"
```

@rsevilla87 and @josecastillolema  I've updated the uperf server to listen on port `30000` for all service types as advised, that avoids complexity in the code.  
### Fixes

2022-01-19 11:54 UTC, jtaleric reviewed
Thanks @mukrishn - only nit is this handles the pod case, but not the VM case... If we want to full-stop move to port 30000 I suggest we modify all the templates.

2022-01-19 14:24 UTC, mukrishn commented
Thanks @jtaleric good point, updated the VM server port and that is the only place I could find. PTAL.

> Thanks @mukrishn - only nit is this handles the pod case, but not the VM case... If we want to full-stop move to port 30000 I suggest we modify all the templates.

2022-01-21 14:24 UTC, jtaleric commented
The only other headache I can think of is we need to open up the ports in each cloud for the testing...

2022-01-21 18:52 UTC, mukrishn commented
> The only other headache I can think of is we need to open up the ports in each cloud for the testing...

Yes, @rsevilla87 already found some and updated https://github.com/cloud-bulldozer/scale-ci-deploy/pull/183

2022-01-24 11:17 UTC, rsevilla87 requested changes
Hey @mukrishn, can you update uperf docs to describe these couple of new scenarios?

On the other hand, I think you can add a test case for the nodePort scenario.

2022-01-24 19:17 UTC, rsevilla87 commented
Hey @mukrishn, tests live now under the e2e directory, check this document https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/e2e-ci.md. The tests directory is there since benchmark-wrapper still uses them.

2022-01-24 19:28 UTC, mukrishn commented
> Hey @mukrishn, tests live now under the e2e directory, check this document https://github.com/cloud-bulldozer/benchmark-operator/blob/master/docs/e2e-ci.md. The tests directory is there since benchmark-wrapper still uses them.

Thanks Raul, now I've included bats for uperf nodeport. PTAL

2022-01-26 17:08 UTC, mohit-sheth approved these changes
LGTM

2022-01-28 15:47 UTC, mohit-sheth commented
/rerun

2022-01-28 15:55 UTC, mohit-sheth commented
/rerun all

2022-01-28 16:10 UTC, mohit-sheth commented
nodeport test is passing

2022-01-28 16:10 UTC, merged